language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t tgbkrkmz/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tgbkrkmz/react-test npm test

after_success:
    - docker build -t tgbkrkmz/multi-client ./client
    - docker build -t tgbkrkmz/multi-nginx ./nginx
    - docker build -t tgbkrkmz/multi-server ./server
    - docker build -t tgbkrkmz/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tgbkrkmz/multi-client
    - docker push tgbkrkmz/multi-nginx
    - docker push tgbkrkmz/multi-server
    - docker push tgbkrkmz/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env:  "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-594152818161"
    bucket_path: "docker-multi"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
